# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2NP13-P1OsaY9aPS6wdsY4fwOVNLHJK
"""

Okay, I understand. You want the UI structure and look-and-feel (as much as Streamlit allows) with all dynamic content and logic being pure placeholders. This means no actual image analysis, no real recommendations, just the interface.

Here's the Streamlit Python code for the UI, with all core functionalities simulated or using placeholder text/images:

Python

import streamlit as st
import random

# --- Page Configuration ---
st.set_page_config(
  layout="wide",
  page_title="Cloud-Powered Recommendation System (UI Simulation)",
  initial_sidebar_state="collapsed"
)

# --- Inject custom CSS for a darker theme and some visual resemblance ---
st.markdown("""
    <style>
    .stApp {
        background-color: #0E1117;
        color: #E6E6E6;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
    .stButton > button {
        background-color: #007bff;
        color: white;
        border-radius: 8px;
        padding: 10px 20px;
        font-size: 1.1em;
        transition: background-color 0.3s ease;
    }
    .stButton > button:hover {
        background-color: #0056b3;
    }
    .stTabs [data-baseweb="tab-list"] {
        gap: 20px;
    }
    .stTabs [data-baseweb="tab"] {
        height: 50px;
        white-space: nowrap;
        background-color: #1a222f;
        border-radius: 4px 4px 0 0;
        padding: 10px 20px;
        border-bottom: 3px solid transparent;
        transition: all 0.3s ease;
    }
    .stTabs [aria-selected="true"] {
        background-color: #0d121c;
        border-bottom: 3px solid #007bff;
        color: #007bff;
    }
    .stTabs [data-baseweb="tab-list"] button [data-testid="stMarkdownContainer"] p {
        font-size: 1.1rem;
        font-weight: bold;
    }
    .stMarkdown h1, .stMarkdown h2, .stMarkdown h3 {
        color: #007bff;
        border-bottom: 1px solid #2d384c;
        padding-bottom: 5px;
        margin-bottom: 15px;
    }
    .stContainer {
        background-color: #1a222f;
        padding: 20px;
        border-radius: 10px;
        margin-bottom: 20px;
    }

    .recommendation-box {
        border: 2px solid #007bff;
        border-radius: 10px;
        padding: 15px;
        margin-bottom: 20px;
        box-shadow: 0 0 15px rgba(0, 123, 255, 0.5);
        background-color: #0d121c;
        text-align: center;
    }
    </style>
""", unsafe_allow_html=True)

# --- Header Section (Top Right like "Bakrieland" and "Powered By") ---
col_header_left, col_header_right = st.columns([0.7, 0.3])
with col_header_right:
    # Placeholder images for logos
    st.image("https://via.placeholder.com/150x50/1a222f/E6E6E6?text=BAKRIELAND", width=150)
    st.markdown("""
        <p style='text-align: right; font-size: 0.8em; color: #888;'>
            POWERED BY <img src='https://via.placeholder.com/50x20/1a222f/E6E6E6?text=G.AI' width='50' style='vertical-align: middle; margin-left: 5px;'>
        </p>
    """, unsafe_allow_html=True)

st.markdown("---")

# --- Main Layout: Three Columns ---
col1, col2, col3 = st.columns([1, 1, 2])

# --- Column 1: Property Recommendation ---
with col1:
    st.markdown("<h2 style='text-align: center;'>PROPERTY RECOMMENDATION</h2>", unsafe_allow_html=True)
    st.markdown("<div class='recommendation-box'>", unsafe_allow_html=True)
    st.image("https://via.placeholder.com/400x250/343a40/FFFFFF?text=PROPERTY+IMAGE+1", caption="KEMIRIPAN PURI WIDYAKARTA", use_column_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

    st.markdown("<div class='recommendation-box'>", unsafe_allow_html=True)
    st.image("https://via.placeholder.com/400x250/343a40/FFFFFF?text=PROPERTY+IMAGE+2", caption="BOGOR PUNCAK RESIDENCE", use_column_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

# --- Column 2: Holiday Recommendation ---
with col2:
    st.markdown("<h2 style='text-align: center;'>HOLIDAY RECOMMENDATION</h2>", unsafe_allow_html=True)
    st.markdown("<div class='recommendation-box'>", unsafe_allow_html=True)
    st.image("https://via.placeholder.com/400x250/343a40/FFFFFF?text=THEMEPARK+IMAGE+1", caption="JUNGLE LAND", use_column_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

    st.markdown("<div class='recommendation-box'>", unsafe_allow_html=True)
    st.image("https://via.placeholder.com/400x250/343a40/FFFFFF?text=OUTBOUND+IMAGE+2", caption="RIVIERA OUTBOUND", use_column_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

# --- Column 3: Image Capture and Mood Analytic ---
with col3:
    st.markdown("<h2 style='text-align: center;'>MOOD ANALYTIC</h2>", unsafe_allow_html=True)

    # --- Image Capture and Display ---
    st.subheader("Capture Your Mood!")
    st.markdown("<p style='font-size:0.9em; color:#bbb;'>Use your camera to take a picture for mood analysis simulation.</p>", unsafe_allow_html=True)
    picture = st.camera_input("Open Camera")

    if picture:
        st.image(picture, caption="Captured Image", use_column_width=True)
        st.info("Image captured. Simulating mood analysis results...")

        # --- Simulated Mood Analysis Results ---
        simulated_moods = ["Happy", "Calm", "Energetic", "Thoughtful", "Brave", "Relaxed"]
        selected_mood = random.choice(simulated_moods)

        st.markdown(f"<h3 style='color:#f0e68c;'>Simulated Mood Detected: **{selected_mood}**</h3>", unsafe_allow_html=True)
        st.markdown("<p style='font-size:0.8em; color:#888;'><i>(This is a placeholder for actual mood detection logic.)</i></p>", unsafe_allow_html=True)

        # --- Mood Analytic Tabs ---
        tab_mood_analysis, tab_property_rec, tab_holiday_rec = st.tabs(["Mood Analysis", "Property", "Holiday Recommendation"])

        with tab_mood_analysis:
            st.markdown(f"""
                <p>Based on a simulated analysis, your mood is: <strong>{selected_mood}</strong>.</p>
                <p>This mood typically correlates with:</p>
                <ul>
                    <li><strong>Outlook:</strong> A generally positive and engaged disposition.</li>
                    <li><strong>Energy Level:</strong> Moderate to high, ready for engagement.</li>
                    <li><strong>Personality Traits:</strong> May include adaptability, curiosity, and a drive for personal fulfillment.</li>
                    <li><strong>Core Feeling:</strong> A sense of well-being and openness.</li>
                </ul>
                <p style='font-size:0.8em; color:#888;'><i>(Detailed mood analysis descriptions would appear here based on real data.)</i></p>
            """, unsafe_allow_html=True)

        with tab_property_rec:
            st.markdown(f"""
                <p>For your simulated <strong>{selected_mood}</strong> mood, a recommended property might be:</p>
                <ul>
                    <li><strong>Type:</strong> Placeholder Modern Villa / Green Residence</li>
                    <li><strong>Description:</strong> This property is envisioned for individuals seeking a blend of comfort, modern aesthetics, and serene environments. It often features spacious interiors, smart home technologies, and access to community green spaces or nature reserves.</li>
                    <li><strong>Key Features:</strong> Large windows for natural light, open-plan living, communal recreation areas, and proximity to wellness facilities.</li>
                </ul>
                <p style='font-size:0.8em; color:#888;'><i>(Specific property recommendations and details would be dynamically generated here.)</i></p>
            """, unsafe_allow_html=True)

        with tab_holiday_rec:
            st.markdown(f"""
                <p>For your simulated <strong>{selected_mood}</strong> mood, a recommended holiday might be:</p>
                <ul>
                    <li><strong>Type:</strong> Placeholder Nature Escape / Urban Exploration</li>
                    <li><strong>Description:</strong> An experience designed to refresh your senses and stimulate your interests, whether through tranquil natural beauty or the vibrant energy of a bustling city. Activities could range from leisurely hikes to cultural tours.</li>
                    <li><strong>Key Activities:</strong> Hiking trails, local culinary experiences, historical site visits, or relaxing spa treatments.</li>
                </ul>
                <p style='font-size:0.8em; color:#888;'><i>(Specific holiday recommendations and details would be dynamically generated here.)</i></p>
            """, unsafe_allow_html=True)
    else:
        st.markdown("""
            <p style='text-align: center; padding-top: 20px; font-size: 1.1em; color: #aaa;'>
                📸 Awaiting image capture... Your mood analysis and recommendations will appear here.
            </p>
        """, unsafe_allow_html=True)

# --- Footer ---
st.markdown("---")
st.markdown("<p style='text-align: center; color: grey; font-size: 0.8em;'>&copy; 2025 Cloud-Powered Recommendation System UI. All rights reserved. (Simulated)</p>", unsafe_allow_html=True)